### ISSUE TITLE
페어프로그래밍

### ISSUE THREAD

**Issue by hanseulhee** [hanseulhee/studying#2]
## 방식

**Driver**는 키보드를 소유하고 있는 사람으로 현재의 작은 목표를 완수하는데 집중합니다. 
**Navigator**는 Driver가 코드를 작성하는 동안 관찰자의 입장으로 코드를 검토하고 지식을 전달하며 생각을 공유합니다.

**뽀모도로 기법(Pomodoro Technique)** 으로 진행합니다. 

## TODO

- [x]  카드 마크업 짜기
- [x]  카드 스타일 적용하기
- [x]  /api/sample/folder api 연결하기
- [x]  카드 클릭 시 해당 링크로 이동하기
- [x]  Date 개발하기

**Comment by hanseulhee** [comment]
4시간 이상 소요되었지만
재밌었던 경험!

**KPT:**
**Keep**
- 적극적으로 의견 공유하며 적용한 점
- 다른 사람의 코드를 보며 많이 배울 수 있었던 점

**Problem**
- 뽀모도로 기법의 시간을 제대로 안 잰 점
- 네트워크 문제가 몇 번 있었던 점

**Try**
- 미리 사용할 라이브러리를 찾아오기
- 클래스명이나 함수명 등 그라운드 룰을 정하고 시작하기
- 할 일을 더 세분화 하기

**Comment by hanseulhee** [comment]
**페어프로그래밍 한 부분**
https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/pull/310

```text
src/components/card/FolderCard.tsx
src/components/card/FolderList.tsx
src/utils/formatDate.ts
src/utils/formatPeriod.ts
src/utils/cutString.ts
```
